// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/knight-admin/IntegratedAdmin.tsx": () => import("../components/mockups/knight-admin/IntegratedAdmin.tsx"),
  "./components/mockups/edge-status/EdgeStatusSelector.tsx": () => import("../components/mockups/edge-status/EdgeStatusSelector.tsx")
};
